language: ruby
env:
  global:
    - GIT_COMMITTER_NAME: "rejasupotaro"
    - GIT_COMMITTER_EMAIL: "takiguchi0817@gmail.com"
    - GIT_AUTHOR_NAME: "rejasupotaro"
    - GIT_AUTHOR_EMAIL: "takiguchi0817@gmail.com"
    - secure: "TLm4LvfiBOqujs1Ihw7PdiPs5vZvz7drEMY8IT115xztaI51iPyIpFnQUYXozrG7Psy7oQd/mBtF2OAj70mmFM24Vh1eQj8eTNJjWLuqiO7aheXVA1qOHJrvlPc/ZfN5SlY2nia14vp0d5oMMkGCjmK8ksaX/mwUcc5q3bL9Kkg="
script:
    - bundle exec rspec
after_success:
    - cd build
    - echo "task :default" > Rakefile
    - git init
    - git add --all
    - git commit -m "Update from Travis CI"
    - 'git push --quiet https://$GITHUB_TOKEN@github.com/rejasupotaro/rejasupotaro.github.io.git master -f 2> /dev/null'
branches:
  only:
    - source
